import {useEffect,useState} from "react";
import {ActivityIndicator,FlatList,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View} from "react-native";
import * as SecureStore from "expo-secure-store";
import Constants from "expo-constants";

const API=Constants.expoConfig?.extra?.apiUrl as string;
type Artisan={id:string;name:string;trade:string;area:string;rating:number};
type Tab="explore"|"jobs"|"post"|"map"|"account";

export default function App(){
  const[tab,setTab]=useState<Tab>("explore");const[artisans,setArtisans]=useState<Artisan[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[role,setRole]=useState<string|null>(null);
  useEffect(()=>{void fetch(`${API}/v1/artisans?available=true`).then(r=>r.json()).then(setArtisans).finally(()=>setLoading(false));void SecureStore.getItemAsync("mafundi_role").then(setRole)},[]);
  const tabs:Tab[]=role==="artisan"?["explore","jobs","map","account"]:role==="admin"?["jobs","map","account"]:["explore","jobs","post","map","account"];
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Text style={styles.brand}>Mafundi.</Text><Text style={styles.pill}>NAIROBI</Text></View><View style={styles.content}>{tab==="explore"&&<><Text style={styles.title}>Trusted help,{`\n`}right around the corner.</Text><TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Plumber, electrician or estate"/>{loading?<ActivityIndicator/>:<FlatList horizontal showsHorizontalScrollIndicator={false} data={artisans.filter(a=>`${a.name} ${a.trade} ${a.area}`.toLowerCase().includes(query.toLowerCase()))} keyExtractor={item=>item.id} renderItem={({item})=><View style={styles.card}><View style={styles.avatar}><Text>{item.name.split(" ").map(p=>p[0]).join("").slice(0,2)}</Text></View><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.muted}>{item.trade} · {item.area}</Text><Text style={styles.rating}>★ {item.rating||"New"}</Text></View>}/>}</>}{tab!=="explore"&&<View style={styles.empty}><Text style={styles.title}>{tab[0].toUpperCase()+tab.slice(1)}</Text><Text style={styles.muted}>{role?`Secure ${role} data loads after sign-in.`:"Sign in to use this workspace."}</Text></View>}</View><View style={styles.nav}>{tabs.map(item=><Pressable key={item} onPress={()=>setTab(item)} style={[styles.navItem,tab===item&&styles.active]}><Text style={tab===item?styles.activeText:styles.navText}>{item}</Text></Pressable>)}</View></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},header:{height:64,paddingHorizontal:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderColor:"#eceeea"},brand:{fontSize:22,fontWeight:"800",letterSpacing:-1},pill:{fontSize:9,fontWeight:"800",backgroundColor:"#d9ff66",paddingHorizontal:9,paddingVertical:5,borderRadius:9},content:{flex:1,padding:20},title:{fontSize:36,fontWeight:"800",letterSpacing:-1.8,lineHeight:39,marginBottom:22},search:{height:54,borderWidth:1,borderColor:"#dfe3dc",borderRadius:16,paddingHorizontal:16,fontSize:15,marginBottom:20},card:{width:250,borderWidth:1,borderColor:"#e4e8e2",borderRadius:20,padding:14,marginRight:12},avatar:{height:150,borderRadius:15,backgroundColor:"#e4f1ea",alignItems:"center",justifyContent:"center"},cardTitle:{fontSize:17,fontWeight:"800",marginTop:13},muted:{fontSize:12,color:"#697069",marginTop:5},rating:{fontSize:12,fontWeight:"800",marginTop:12},empty:{flex:1,justifyContent:"center"},nav:{height:72,flexDirection:"row",alignItems:"center",justifyContent:"space-around",borderTopWidth:1,borderColor:"#e5e8e3",paddingHorizontal:8},navItem:{padding:10,borderRadius:12},active:{backgroundColor:"#101310"},navText:{fontSize:10,color:"#4f554f",textTransform:"capitalize"},activeText:{fontSize:10,color:"#fff",textTransform:"capitalize",fontWeight:"800"}});
